name: PR Checks

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn validate:json
        name: Validate Song Data
      - run: yarn validate:ts
        name: Validate Types
      - run: yarn webpack
        name: Build App
